stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: node:18-alpine
  script:
    - echo "install dependecies"
    - npm ci
    - echo "running build"
    - npm run build
  artifacts:
    paths:
      - build/

test_job:
  stage: test
  image: node:18-alpine
  script:
    - echo "test"
    - npm ci
    - npm run test

deploy_job:
  stage: deploy
  script:
    - echo "deploy"